language: php
sudo: false

php:
- 5.6
- 5.5
- 7

services:
- redis-server

before_script:
- composer self-update
- composer install --no-interaction
- redis-server --version

script:
- vendor/bin/phpunit

matrix:
fast_finish: true